FROM node:14.18-alpine as build

ADD ./front /app/front
ADD ./package.json /app/package.json
ADD ./build /app/build
ADD ./config_webpack /app/config_webpack
WORKDIR /app
RUN npm i && npm run build
ADD ./static /app/static

FROM nginx:1.19.10 as app
COPY --from=build ./app/dist /usr/share/nginx/html
COPY nginx/default.conf.template /etc/nginx/templates/default.conf.template
ENV SERVER_PORT=80
