version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8085:80"

  database:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dental -d nlp"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dental
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nlp
